### ISSUE TITLE
Consider tagging the lastest release with the version

### ISSUE THREAD

**Issue by MinDBreaK** [cytopia/docker-ansible#106]
Hi,

Would it be possible to consider tagging the latest version of the images with the ansible version ? 
Currently, latest is 1.12, but when 1.13 will be out, then latest will point toward this version and might break CI or scripts using it. While I'm in favor for rapid upgrades, those have to be tested first.

Tagging the latest release also with the current version will allow for better stability and easier migrations. 

Thank you for your project and your work.

**Comment by cytopia** [comment]
@MinDBreaK Have a look at Point in time releases for that: https://github.com/cytopia/docker-ansible#new-point-in-time-releases

The latest tag will always point to the latest nightly build.
