### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by dolohow** [cytopia/docker-ansible#110]
I am getting error:
```
AnsibleError: template error while templating string: No filter named 'ansible.utils.ipmath'
```

**Comment by cytopia** [comment]
@dolohow What is meant by `Bump version` and how can I reproduce this error locally?

**Comment by cytopia** [comment]
@dolohow closing as I don't really know what is meant by this issue. Feel free to add some details

**Comment by cytopia** [comment]
So new versions are pushed to dockerhub again on a nightly basis. What should be "bumped" exactly and what is meant by "bumped"? Can you give an example.

**Comment by dolohow** [comment]
Since they are pushed to docker hub on nightly basis then its all good.  Used to be that docker image was very old.

**Comment by cytopia** [comment]
OK, just for final clarification. There are rolling docker tags (which update nightly): https://github.com/cytopia/docker-ansible#repeat-rolling-releases and also Point-in-time tags, which are only pushed once upon git tag creation: https://github.com/cytopia/docker-ansible#new-point-in-time-releases
