### ISSUE TITLE
How can I downgrade git version in the docker

### ISSUE THREAD

**Issue by hmpargi** [cytopia/docker-ansible#121]
Hi All,
How do i downgrade git version. it shows 2.36.3
I need 2.30

I try many ways doesnt work apk add git=2.30

**Comment by cytopia** [comment]
The alpine Docker images use Alpine 3.16. Looking at the Alpine package page: https://pkgs.alpinelinux.org/packages?name=git&branch=v3.16&repo=&arch=&maintainer= git is only available in version `2.36.3-r0` So you are out of luck using the `apk` command.

You could compile git from source: https://gist.github.com/samrocketman/8671036
