### ISSUE TITLE
/home/ansible/.ssh doesn't have 700 permissions

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cytopia/docker-ansible#26]
I want to run an `sshd` inside your container image and discovered that the mentioned directory has too wide permissions. An `authorized_keys` file in there will not be accepted by `sshd` unless the folder has 700 permissions.

**Comment by cytopia** [comment]
Can you specify the specific image used, its full run arguments.
I just checked with one of those images and get this:

```
bash-4.4# cd /home/ansible/
bash-4.4# ls -lap
total 20
drwxr-sr-x    5 ansible  ansible       4096 Sep  5 11:02 ./
drwxr-xr-x    1 root     root          4096 Sep  5 11:02 ../
drwx------    2 ansible  ansible       4096 Sep  5 11:02 .aws/
drwx------    2 ansible  ansible       4096 Sep  5 11:02 .gnupg/
drwxr-xr-x    2 ansible  ansible       4096 Sep  5 11:02 .ssh/
```

**Comment by MarkusTeufelberger** [comment]
I'm running `cytopia/ansible:2.8-awsk8s`.

In your output you can see that this is with 755 permissions (it is explicitly defined that way in the Dockerfiles). I'd like to change the https://github.com/cytopia/docker-ansible/blob/992ca407e57fc67a214425ee0ae6858f27811982/Dockerfile-awsk8s#L86 line to `&& chmod 0700 /home/ansible/.ssh \`

**Comment by cytopia** [comment]
OK, now I understood correctly, can u please create a PR for that. Looks good with me.
