### ISSUE TITLE
add paramiko to the `tools` flavor?

### ISSUE THREAD

**Issue by hellt** [cytopia/docker-ansible#42]
Hi,
will it be possible to consider to include `paramiko` python module to the `tools` flavor? This module is handy to have for local actions that use networking modules of ansible

**Comment by cytopia** [comment]
As I understood correctly from their website, this tool allows for Python based SSH connections. Wouldn't it make more sense to put it into `infra` instead. Or is there a need to require it in any of the cloud images as well?

**Comment by hellt** [comment]
@cytopia yes, `infra` would do as well, thanks!
