### ISSUE TITLE
home directory not being rebuilt when specifying UID

### ISSUE THREAD

**Issue by asharpe** [cytopia/docker-ansible#44]
```
docker run --rm -it -v $(pwd):/data -v ssh-agent:/ssh-agent -e USER=ansible -e UID=501 cytopia/ansible:2.6-tools /bin/bash
[INFO] Running container with user 'ansible'
[INFO] Changing UID to 501
[INFO] Adjusting local user with uid:501 and gid:1000
[INFO] ansible> /bin/bash
bash-4.4$ ls -la ~
total 16
drwxr-sr-x    4 ansible  ansible       4096 Nov 27 00:29 .
drwxr-xr-x    4 root     root          4096 Nov 28 11:38 ..
drwx------    2 1000     ansible       4096 Nov 27 00:29 .gnupg
drwx------    2 1000     ansible       4096 Nov 27 00:29 .ssh
```

observe that the .gnupg and .ssh directories are still owned by uid 1000

I would expect that the owner of these directories is ansible, and my suspicion is that `deluser` requires the `--remove-home` option when used in `/docker-entrypoint.sh`

```
bash-4.4$ deluser --help
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: deluser [--remove-home] USER

Delete USER from the system
```

**Comment by asharpe** [comment]
This might not be a good idea, and won't work if something is mounted in those locations.  I guess a good starting question is: why make .gnupg and .ssh directories in the tools image?

If we're going to remove the home directory, we're probably going to need to recreate those other directories as well, so why not move the creation of them entirely into `/docker-entrypoint.sh` and leave them out of the build process?

**Comment by asharpe** [comment]
I've just learned the hard way why you don't want to remove directories in `/docker-entrypoint.sh`

**Comment by cytopia** [comment]
I will take a look at the permission issue.

> I've just learned the hard way why you don't want to remove directories in /docker-entrypoint.sh

what happened?

**Comment by asharpe** [comment]
I had my host .ssh directory mounted in the container and added the
--remove-home option which nuked the contents of my .ssh :)
