### ISSUE TITLE
Include OpenShift oc CLI?

### ISSUE THREAD

**Issue by etoews** [cytopia/docker-ansible#55]
These are some great images. Exactly the sort of thing I've been looking for. Thanks!

In your awsk8s flavour, I see you've included the openshift lib. Would you be interested in including the OpenShift oc CLI too?

I've already got a branch that does it, see https://github.com/cytopia/docker-ansible/compare/master...etoews:oc

Note how the oc binary is dynamically linked so getting it to run in Alpine requires a workaround. 

Here are the related issues:

* https://github.com/openshift/origin/issues/18942
* https://github.com/openshift/origin/issues/11135

I don't think Red Hat will be providing a statically linked oc binary any time soon.

If you're interested, I could send a PR.

**Comment by cytopia** [comment]
@etoews will be added here: https://github.com/cytopia/docker-ansible/pull/58
