### ISSUE TITLE
All flavours should contain rsync

### ISSUE THREAD

**Issue by pmyjavec** [cytopia/docker-ansible#64]
Hello,

Proposing that all flavors add rsync, without it, the synchronization module does not work, building a customer layer is always an option but it still seems as if a critical component is missing.

**Comment by Hipska** [comment]
It is available in the [infra](https://github.com/cytopia/docker-ansible#ansible-infra) flavor.

**Comment by cytopia** [comment]
@pmyjavec did you try the infra flavour as @Hipska was suggesting?

**Comment by cytopia** [comment]
@pmyjavec going to close this due to lack of activity/response. Feel free to post if the suggestion from @Hipska satsified your needs or otherwise we can discuss how to proceed differently.
