### ISSUE TITLE
Add lxml junit-xml

### ISSUE THREAD

**Issue by ryanmerolle** [cytopia/docker-ansible#70]
First of all, I appreciate the collection of images you maintain!  Thanks!

Given [GitLab-CI junit test reporting](https://docs.gitlab.com/ee/ci/unit_test_reports.html), it would be nice to package lxml and junit-xml with the ansible images.

**Comment by cytopia** [comment]
@ryanmerolle thanks for the hint. Aren't those packages something that should rather go into a separate Docker image specifically for that?

**Comment by ryanmerolle** [comment]
First, I appreciate the prompt response and conversation.  If you ran a job in a pipeline that executed a playbook, you can set the appropriate ansible.cfg and Environment variables to enable the junit plugin to output an additional junit summary file at the end of the play.

Since the plugin can only write output for that play, if you used another container, you would need some way for the play to persist and move to the new container.  Regardless, ansible would still need to be on this new junit enabled container as well.

**Comment by cytopia** [comment]
I will give it a shot here: https://github.com/cytopia/docker-ansible/pull/71

**Comment by ryanmerolle** [comment]
@cytopia thanks!  Gitlab reports now work because the ansible container has the dependencies required for outputting junit tests.

Example: https://gitlab.com/ryanmerolle/avd-demo/-/pipelines/306599182/test_report

**Comment by cytopia** [comment]
Glad to hear :-)
