### ISSUE TITLE
support hashicorp consul and vault

### ISSUE THREAD

**Issue by acelinkit** [cytopia/docker-ansible#72]
**SUMMARY:**
This request is for adding `python-consul` and `hvac` python libraries to support Ansible lookups to HashiCorp Consul/Vault.  

**CONTEXT:**
HashiCorp Consul and HashiCorp Vault are powerful development tools for storing secrets/configurations and widely used across the industry.  Ansible offers lookup modules for these tools, however they require additional packages on the Ansible controller to use.   

**DETAILS:**
consul_kv_lookup
https://docs.ansible.com/ansible/latest/collections/community/general/consul_kv_lookup.html
requires: python-consul2 python library
https://www.consul.io/api-docs/libraries-and-sdks

community.hashi_vault.hashi_vault
https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup
requires: hvac python library
https://www.vaultproject.io/api-docs/libraries

edit: updating to python-consul2 library + links to libraries

**Comment by acelinkit** [comment]
Can open a MR if this request is accepted and flavor is specified.

**Comment by cytopia** [comment]
Thanks for this suggestion. I will look into this regarding size and potential flavour to use (I am currently close to GitHub Action limit in regards to available different builds to trigger)

**Comment by acelinkit** [comment]
It was enough to use both of those.  Going to close issue, tools are pretty specific and not needed in a general image
