### ISSUE TITLE
ansible collection issues in 2.11 tags

### ISSUE THREAD

**Issue by ryanmerolle** [cytopia/docker-ansible#92]
It seems that tags using 2.10 leverage the default ansible collection location path `/usr/lib/python3.8/site-packages/ansible_collections`.

It seems that tags using 2.10 leverage the default ansible collection location path `/root/.ansible/collections:/usr/share/ansible/collections`.  The problem with this is that if you run a playbook or run the command `ansible-galaxy collection list` ansible does not see this new path for some reason and collections cannot be found.

This effectively makes collection usage with 2.11 unusable.

**Comment by cytopia** [comment]
@ryanmerolle thanks for the reporting an issue here

* Can you clarify which of the two paths you are talking about for version 2.10?
* How would I be able to see the defined path?
* What should the path be to use collections?
* Can't you use ansible.cfg to override the path?

**Comment by ryanmerolle** [comment]
I should probably have better documented the issue.  Apologies.

I created an empty gitlab project with just the gitlab-ci file running the same steps for each container.  This should help clarify:

https://gitlab.com/ryanmerolle/ansible-ci-test

https://gitlab.com/ryanmerolle/ansible-ci-test/-/pipelines/402290704

**Comment by cytopia** [comment]
@ryanmerolle I currently have zero experience with Ansible collections.
 
After some research I figured that collections are pre-installed on Ansible 2.10 docker image, but not on Ansible 2.11 docker image.

One way to install whatever collections are required for Ansible 2.11 docker image is:
```
# Install
docker run -it --rm -v $(pwd):/root/.ansible cytopia/ansible:2.11 ansible-galaxy collection install amazon.aws

# List installed collections
docker run -it --rm -v $(pwd):/root/.ansible cytopia/ansible:2.11 ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection Version
---------- -------
amazon.aws 2.0.0
```

**Comment by cytopia** [comment]
If collections are treated the same way as roles, then they should most likely reside outside the docker image and live in your repository (git-ignored). This way you can pin specific versions for your project just as you do with Ansible roles.

**Comment by ryanmerolle** [comment]
Hello @cytopia I currently do as you say.  Collections are just a packaged up group of roles with complimentary plugins and possibly filters.

I store my collections in a repo or leverage the ansible-galaxy repo for official collections.

My workflow has always been to install collections referencing a requirements.yml that pins to a specific version.  It works fine with the 2.10 version of this container and not the 2.11 version.  When I dug into it, I noticed the ansible-collection path was different than the default if I setup ansible myself.  Instead of giving you all the workflow specifics, I jumped into the clear differences between the two behaviors in the images.

Let me dig into this to discover the full root cause and come back to you with a possible PR.

Thanks!

**Comment by ryanmerolle** [comment]
It all makes sense now that I dug into the Dockerfiles.

2.10 uses `ansible` (the fat package with all the "approved" collections included).

2.11 uses `ansible-core` (the thin package without all the "approved" collections included).

Basically this is a change in approach.  If 2.10 used `ansible-base` (what ansible-core was renamed from) then 2.10 and 2.11 would have similar behaviors.  I used the 2.10 image to with gitlab-ci to run docker & docker-compose based workflows without having to install the docker collection for docker.  This explains the smaller image size for 2.11, which again makes perfect sense.

Its just odd that ansible-galaxy collection list usually just lists no collections if nothing is in the path instead of the error I saw.


I'm hesitant to make a PR here given, but the change from 2.10 to 2.11 does cause some confusion.

**Comment by cytopia** [comment]
Prio Ansible 2.11, The PyPi ansible package went by the same version as Ansible was (e.g.: `pip3 install ansible==2.10.x`).
Then they bumed the versions of the PyPi ansible package to unrelated numbers and I had to `ansible-core` package.

I rather also want the core collections to be part of it again. Do you know what PyPi package provides the collections?

**Comment by ryanmerolle** [comment]
[Ansible Roadmap](https://docs.ansible.com/ansible/devel/roadmap/ansible_roadmap_index.html)

| Ansible | Ansible Core |
| ------- | ------------- |
| 2.10 | 2.10 (ansible-base)|
| 3.0 | 2.10 |
| 4.0 | 2.11 |
| 5.0 (comes out this month) | 2.12 (comes out this month) |

**Comment by theHilikus** [comment]
is there a plan to release a 4.0 image? TBH, now that image 2.11+ comes with `ansible-core` (no collections), the image is much less useful since you would need to install a bunch of collections to make it useful again
